"""Assemble the survey sections into one draft document."""

from __future__ import annotations

from pathlib import Path

SECTION_ORDER = [
    ("01-introduction.md", "# §1 Introduction"),
    ("02-method.md", "# §2 Method"),
    ("03-foundations.md", "# §3 Foundations"),
    ("04-test-time-compute.md", "# §4 Test-Time Compute"),
    ("05-cross-pillar.md", "# §5 Cross-Pillar Convergence"),
    ("06-empirical-trends.md", "# §6 Empirical Trends"),
    ("07-open-problems.md", "# §7 Open Problems"),
]

DRAFT_HEADER = """# The Compute-Allocation Frontier: A Living, Reproducible Survey of LLM Reasoning and Test-Time Compute

> **Draft v0.1 (assembled {date})** — generated by the Evergreen Research
> corpus pipeline. Sections cite `evg-*` records from `data/papers.jsonl`;
> only full-text-verified records may survive into the final version.
> Position, risks, and the submission gate: see `positioning.md`.

Large language models are shifting from train-time to test-time scaling:
reasoning models now spend deliberate compute at inference through long
chains of thought, learned search, and verifier-guided refinement, trained
via reinforcement learning with verifiable rewards (RLVR). Yet the field's
existing surveys are static snapshots written by individual teams at a
single moment, and they treat test-time compute in isolation from the rest
of frontier AI. This paper presents a living, reproducible survey of LLM
reasoning and test-time compute, generated by a continuously-updating arXiv
corpus pipeline that sweeps six pillars weekly into an append-only,
evidence-linked paper database. We organize the field under a unifying
compute-allocation lens — where compute is spent across training versus
inference, in the model versus the environment, and on representation
versus reward. We document the full RLVR stack, from verifiers and process
reward models to search strategies and inference-time scaling laws, and
trace how these methods converge across agentic deep research, efficient
inference, alignment, multimodal/world models, and quantitative finance.
Every claim links to a verifiable paper record, making the survey auditable
and updatable rather than a frozen artifact. We close with open problems
and a forecast of the test-time-compute frontier.

---
"""


def assemble(survey_root: Path) -> Path:
    """Concatenate sections in order into data/survey/draft.md."""
    from datetime import date

    sections = survey_root / "sections"
    parts: list[str] = [DRAFT_HEADER.format(date=date.today().isoformat())]
    for filename, heading in SECTION_ORDER:
        path = sections / filename
        if path.exists():
            parts.append(f"<!-- {filename} -->\n")
            parts.append(path.read_text(encoding="utf-8").strip() + "\n\n")
        else:
            parts.append(f"{heading}\n\n> (pending)\n\n")
    draft = survey_root / "draft.md"
    draft.write_text("\n".join(parts), encoding="utf-8")
    return draft
