"""Render weekly digests, the master index, the survey outline, and the
GitHub Pages landing from the paper database."""

from __future__ import annotations

import json
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from evergreen.database import PaperDatabase
from evergreen.pillars import PILLARS


def iso_week() -> str:
    now = datetime.now(UTC)
    year, week, _ = now.isocalendar()
    return f"{year}-W{week:02d}"


def _paper_lines(records: list[dict[str, Any]], pillar: str) -> list[str]:
    papers = [record for record in records if record.get("pillar") == pillar]
    if not papers:
        return ["- (no papers in this window)\n"]
    lines: list[str] = []
    for record in papers[:15]:
        arxiv_short = record.get("arxiv_id", "").split("/abs/")[-1] or "arXiv"
        methods = ", ".join(record.get("methods", [])[:3]) or "—"
        benchmarks = ", ".join(record.get("benchmarks", [])[:4]) or "—"
        lines.append(
            f"- **{record['title']}** ([{arxiv_short}]({record.get('url', '')})) — "
            f"conf {record.get('confidence', 0):.2f} · {methods} · benchmarks: {benchmarks}"
        )
    if len(papers) > 15:
        lines.append(f"- …and {len(papers) - 15} more papers in this pillar.")
    return lines


def write_weekly(db: PaperDatabase, summary: dict[str, Any], weekly_root: Path) -> Path:
    weekly_root.mkdir(parents=True, exist_ok=True)
    path = weekly_root / f"{iso_week()}.md"
    records = [record for record in db.load() if record.get("swept_on") == summary["swept_on"]]

    lines: list[str] = [
        f"# Frontier AI Weekly — {iso_week()}",
        "",
        f"> swept {summary['fetched']} papers ({summary['new_records']} new) · "
        f"database total {summary['total_db']} · generated by Evergreen Research",
        ">",
        "> Evidence is abstract-level (arXiv metadata). Treat claims as research signals.",
        "",
    ]
    for pillar in PILLARS:
        lines.append(f"## {pillar}")
        lines.append("")
        lines.extend(_paper_lines(records, pillar))
        lines.append("")

    if summary["signals"]:
        lines.append("## Cross-Pillar Convergence Signals")
        lines.append("")
        for signal in summary["signals"]:
            lines.append(f"- **{signal['claim']}**")
            lines.append(f"  - spanning: {', '.join(signal['spanning_pillars'])}")
        lines.append("")

    if summary["failures"]:
        lines.append("## Degraded Pillars This Week")
        lines.append("")
        for failure in summary["failures"]:
            lines.append(f"- {failure}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by [Evergreen Research](https://github.com/) — "
                 "human review required before external citation._")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_index(db: PaperDatabase, data_root: Path) -> Path:
    records = db.load()
    stats = db.stats()
    by_pillar = {pillar: [] for pillar in PILLARS}
    for record in records:
        if record.get("pillar") in by_pillar:
            by_pillar[record["pillar"]].append(record)

    lines: list[str] = [
        "# Evergreen Research Index",
        "",
        f"- Total papers: **{stats['total_papers']}**",
        f"- Last sweep: {stats['newest_swept_on'] or 'never'}",
        f"- Top methods: {', '.join(f'{k} ({v})' for k, v in list(stats['top_methods'].items())[:8])}",
        "",
    ]
    for pillar, pillar_records in by_pillar.items():
        lines.append(f"## {pillar} ({len(pillar_records)})")
        lines.append("")
        for record in sorted(pillar_records, key=lambda r: r.get("published", ""), reverse=True)[:25]:
            arxiv_short = record.get("arxiv_id", "").split("/abs/")[-1] or ""
            lines.append(
                f"- {record['title']} — [{arxiv_short}]({record.get('url', '')}) "
                f"({record.get('year', '')})"
            )
        lines.append("")

    lines.append("## Weekly digests")
    lines.append("")
    weekly_dir = data_root / "weekly"
    if weekly_dir.exists():
        for digest in sorted(weekly_dir.glob("*.md"), reverse=True):
            lines.append(f"- [{digest.name}](weekly/{digest.name})")
    path = data_root / "index.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_docs_landing(db: PaperDatabase, docs_root: Path) -> Path:
    """Regenerate the GitHub Pages landing page."""
    docs_root.mkdir(parents=True, exist_ok=True)
    stats = db.stats()
    records = db.recent(8)
    weekly_links = ""
    weekly_dir = docs_root.parent / "data" / "weekly"
    if weekly_dir.exists():
        digests = sorted(weekly_dir.glob("*.md"), reverse=True)[:4]
        weekly_links = "\n".join(
            f"- [Frontier AI Weekly {digest.stem}](../data/weekly/{digest.name})"
            for digest in digests
        )

    lines: list[str] = [
        "# 🌲 Evergreen Research",
        "",
        "A self-updating, continuously running frontier-AI research intelligence.",
        "Weekly arXiv sweeps · living paper database · growing systematic survey.",
        "",
        f"**{stats['total_papers']} papers tracked** across 6 pillars · "
        f"last sweep {stats['newest_swept_on'][:10] or 'pending'}",
        "",
        "## Latest papers",
        "",
    ]
    for record in records:
        arxiv_short = record.get("arxiv_id", "").split("/abs/")[-1] or ""
        lines.append(
            f"- **{record['title']}** ([{arxiv_short}]({record.get('url', '')})) — "
            f"{record.get('pillar', '')}"
        )
    lines.extend(
        [
            "",
            "## Weekly digests",
            "",
            weekly_links or "- (first sweep pending)",
            "",
            "## Repository",
            "",
            "- [Source & methodology](https://github.com/)",
            "- [Paper database](../data/papers.jsonl)",
            "- [Survey outline](../data/survey/outline.md)",
        ]
    )
    path = docs_root / "index.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_survey_outline(db: PaperDatabase, survey_root: Path) -> Path:
    """Keep the survey skeleton in sync with the database."""
    survey_root.mkdir(parents=True, exist_ok=True)
    stats = db.stats()
    total = stats["total_papers"]
    counter = Counter(
        record.get("pillar", "?") for record in db.load()
    )
    lines: list[str] = [
        "# Frontier AI — Living Survey Outline",
        "",
        f"Status: evidence-accumulating (v0.1). {total} papers in corpus.",
        "",
        "## 1. Introduction",
        "- [ ] Scope: six pillars of frontier AI research",
        "- [ ] Method: reproducible weekly arXiv corpus pipeline",
        "- [ ] Contributions: living evidence base + cross-pillar signals",
        "",
        "## 2. Taxonomy",
        "",
    ]
    for pillar in PILLARS:
        lines.append(f"- [ ] {pillar} — {counter.get(pillar, 0)} papers")
    lines.extend(
        [
            "",
            "## 3. LLM Reasoning / Test-time Compute (lead pillar)",
            "- [ ] Chain-of-thought to RLVR: the paradigm shift",
            "- [ ] Verifiers and process reward models",
            "- [ ] Inference-time scaling laws",
            "",
            "## 4. Cross-Pillar Convergence",
            "- [ ] Methods migrating across subfields (see weekly signals)",
            "",
            "## 5. Open Problems",
            "- [ ] to be derived from full-text review",
            "",
            "## 6. Conclusion",
            "",
            "---",
            "_Every section claim must cite paper records from `data/papers.jsonl`._",
        ]
    )
    path = survey_root / "outline.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
