"""Minimal Markdown -> LaTeX converter for the survey draft (stdlib-only).

Covers the markdown subset used by the survey sections: ##/### headings,
unordered lists, bold, inline code, links, blockquotes, and pipe tables.
"""

from __future__ import annotations

import re
from pathlib import Path

TITLE = "The Compute-Allocation Frontier: A Living, Reproducible Survey of LLM Reasoning and Test-Time Compute"

ABSTRACT = (
    "Large language models are shifting from train-time to test-time scaling: "
    "reasoning models now spend deliberate compute at inference through long "
    "chains of thought, learned search, and verifier-guided refinement, trained "
    "via reinforcement learning with verifiable rewards (RLVR). Yet the field's "
    "existing surveys are static snapshots written by individual teams at a "
    "single moment, and they treat test-time compute in isolation from the rest "
    "of frontier AI. This paper presents a living, reproducible survey of LLM "
    "reasoning and test-time compute, generated by a continuously-updating arXiv "
    "corpus pipeline that sweeps six pillars weekly into an append-only, "
    "evidence-linked paper database. We organize the field under a unifying "
    "compute-allocation lens---where compute is spent across training versus "
    "inference, in the model versus the environment, and on representation "
    "versus reward. Every claim links to a verifiable paper record, making the "
    "survey auditable and updatable rather than a frozen artifact."
)

SECTION_FILES = [
    "01-introduction.md",
    "02-method.md",
    "03-foundations.md",
    "04-test-time-compute.md",
    "05-cross-pillar.md",
    "06-empirical-trends.md",
    "07-open-problems.md",
]

_ESCAPE_RE = re.compile(r"([&%$#_])")

_UNICODE_MAP = {
    "\u2265": r"$\geq$",   # >=
    "\u2264": r"$\leq$",   # <=
    "\u2192": r"$\rightarrow$",  # ->
    "\u00d7": r"$\times$",       # x
    "\u00b1": r"$\pm$",
    "\u2248": r"$\approx$",
    "\u2260": r"$\neq$",
    "\u03c9": r"$\omega$",
    "\u2014": "---",  # em dash
    "\u2013": "--",   # en dash
    "\u201c": "``",
    "\u201d": "''",
    "\u2018": "`",
    "\u2019": "'",
    "\u2026": r"\ldots",
    "\u00a7": r"\S",
    "\u26a0": r"\textsuperscript{[re-verify]}",  # warning sign
}


def _escape(text: str) -> str:
    # Braces are deliberately not escaped: inline-code conversion injects
    # \texttt{} wrappers that must survive, and literal braces in the
    # survey text are effectively nonexistent.
    # Order matters: escape specials first, THEN map unicode, so the math
    # delimiters the map injects ($...$) are not re-escaped.
    text = _ESCAPE_RE.sub(r"\\\1", text)
    for source, target in _UNICODE_MAP.items():
        text = text.replace(source, target)
    return text


def _inline(text: str) -> str:
    text = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", text)
    text = re.sub(r"`([^`]+)`", r"\\texttt{\1}", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\\href{\2}{\1}", text)
    return text


def _table_to_latex(lines: list[str]) -> str:
    """Convert consecutive pipe-table lines into a tabular block."""
    rows = []
    for line in lines:
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if all(re.fullmatch(r":?-{2,}:?", cell) for cell in cells):
            continue  # separator row
        rows.append(cells)
    if not rows:
        return ""
    ncols = max(len(row) for row in rows)
    header = rows[0]
    spec = "l" * ncols
    parts = [f"\\begin{{table}}[h]\\centering\\begin{{tabular}}{{{spec}}}", "\\hline"]
    parts.append(" & ".join(_escape(_inline(cell)) for cell in header) + " \\\\")
    parts.append("\\hline")
    for row in rows[1:]:
        padded = (row + [" "] * ncols)[:ncols]
        parts.append(" & ".join(_escape(_inline(cell)) for cell in padded) + " \\\\")
    parts.append("\\hline\\end{tabular}\\end{table}")
    return "\n".join(parts)


def md_to_latex(text: str) -> str:
    out: list[str] = []
    lines = text.split("\n")
    index = 0
    in_list = False
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        if stripped.startswith("|"):
            table_lines = []
            while index < len(lines) and lines[index].strip().startswith("|"):
                table_lines.append(lines[index])
                index += 1
            if in_list:
                out.append("\\end{itemize}")
                in_list = False
            out.append(_table_to_latex(table_lines))
            out.append("")
            continue
        if stripped.startswith("###"):
            if in_list:
                out.append("\\end{itemize}")
                in_list = False
            out.append(f"\\subsection{{{_escape(stripped[3:].strip())}}}")
        elif stripped.startswith("##"):
            if in_list:
                out.append("\\end{itemize}")
                in_list = False
            out.append(f"\\section{{{_escape(stripped[2:].strip())}}}")
        elif stripped.startswith("#"):
            if in_list:
                out.append("\\end{itemize}")
                in_list = False
            out.append(f"\\section*{{{_escape(stripped[1:].strip())}}}")
        elif stripped.startswith("- "):
            if not in_list:
                out.append("\\begin{itemize}")
                in_list = True
            out.append(f"\\item {_escape(_inline(stripped[2:]))}")
        elif stripped.startswith(">"):
            quote_lines = []
            while index < len(lines) and lines[index].strip().startswith(">"):
                quote_lines.append(lines[index].strip()[1:].strip())
                index += 1
            index -= 1
            out.append(
                "\\begin{quote}"
                + " ".join(_escape(_inline(line)) for line in quote_lines)
                + "\\end{quote}"
            )
        elif not stripped:
            if in_list:
                out.append("\\end{itemize}")
                in_list = False
            out.append("")
        else:
            if in_list:
                out.append("\\end{itemize}")
                in_list = False
            out.append(_escape(_inline(stripped)))
            out.append("")
        index += 1
    if in_list:
        out.append("\\end{itemize}")
    return "\n".join(out)


def build_tex(survey_root: Path) -> Path:
    """Assemble data/survey/arxiv/main.tex from the section files."""
    arxiv_dir = survey_root / "arxiv"
    arxiv_dir.mkdir(parents=True, exist_ok=True)
    sections = survey_root / "sections"

    body: list[str] = []
    for filename in SECTION_FILES:
        path = sections / filename
        if not path.exists():
            continue
        body.append(f"% ---- {filename} ----")
        body.append(md_to_latex(path.read_text(encoding="utf-8")))
        body.append("")

    tex = f"""\\documentclass[11pt]{{article}}
\\usepackage[a4paper,margin=1in]{{geometry}}
\\usepackage{{amsmath,amssymb}}
\\usepackage{{hyperref}}
\\usepackage{{graphicx}}
\\usepackage{{booktabs}}
\\usepackage{{microtype}}

\\title{{{TITLE}}}
\\author{{Pengyi Research\\\\ \\small P-Research (living corpus pipeline) \\\\ \\small \\texttt{{github.com/p-research}}}}
\\date{{Draft v0.1 -- generated \\today}}

\\begin{{document}}
\\maketitle

\\begin{{abstract}}
{ABSTRACT}
\\end{{abstract}}

{chr(10).join(body)}

\\section*{{Acknowledgments}}
This survey is generated by an open-source, continuously-updating arXiv
corpus pipeline. The full database, weekly digests, and verification
metadata are released under CC BY 4.0. All claims cite corpus records;
only full-text-verified records are treated as evidence.

\\end{{document}}
"""
    path = arxiv_dir / "main.tex"
    path.write_text(tex, encoding="utf-8")
    return path
